// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sources_proto/SubscribeReq.proto

package com.lol.demo.encode.protobuf;

public final class SubscribeReqProto {
    private static com.google.protobuf.Descriptors.Descriptor
            internal_static_netty_SubscribeReq_descriptor;
    private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_netty_SubscribeReq_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.Descriptor
            internal_static_netty_ProtoHeader_descriptor;
    private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_netty_ProtoHeader_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.Descriptor
            internal_static_netty_ProtoBody_descriptor;
    private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_netty_ProtoBody_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.Descriptor
            internal_static_netty_ProtoBody_HeaderMapEntry_descriptor;
    private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_netty_ProtoBody_HeaderMapEntry_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        String[] descriptorData = {
                "\n sources_proto/SubscribeReq.proto\022\005nett" +
                        "y\"R\n\014SubscribeReq\022\"\n\006header\030\001 \001(\0132\022.nett" +
                        "y.ProtoHeader\022\036\n\004body\030\002 \001(\0132\020.netty.Prot" +
                        "oBody\"\201\002\n\013ProtoHeader\022\020\n\010subReqID\030\001 \001(\005\022" +
                        "+\n\007msgType\030\002 \001(\0162\032.netty.ProtoHeader.Msg" +
                        "Type\"\262\001\n\007MsgType\022\013\n\007DEFAULT\020\000\022\r\n\tLOGIN_R" +
                        "EQ\020\001\022\016\n\nLOGIN_RESP\020\002\022\014\n\010LOGIN_OK\020\003\022\031\n\025LO" +
                        "GIN_OUT_OF_WHITE_IP\020\004\022\016\n\nLOGIN_DENY\020\005\022\021\n" +
                        "\rHEARTBEAT_REQ\020\006\022\022\n\016HEARTBEAT_RESP\020\007\022\014\n\010" +
                        "GAME_REQ\020\010\022\r\n\tGAME_RESP\020\t\"\276\001\n\tProtoBody\022",
                "\020\n\010userName\030\001 \001(\t\022\023\n\013productName\030\002 \001(\t\022\017" +
                        "\n\007address\030\003 \003(\t\0223\n\nheader_map\030\004 \003(\0132\037.ne" +
                        "tty.ProtoBody.HeaderMapEntry\032D\n\016HeaderMa" +
                        "pEntry\022\013\n\003key\030\001 \001(\t\022!\n\005value\030\002 \001(\0132\022.net" +
                        "ty.ProtoHeader:\0028\001B2\n\035com.yzh.netty.enco" +
                        "de.protobufB\021SubscribeReqProtob\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner
                );
        internal_static_netty_SubscribeReq_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_netty_SubscribeReq_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_netty_SubscribeReq_descriptor,
                new String[]{"Header", "Body",});
        internal_static_netty_ProtoHeader_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_netty_ProtoHeader_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_netty_ProtoHeader_descriptor,
                new String[]{"SubReqID", "MsgType",});
        internal_static_netty_ProtoBody_descriptor =
                getDescriptor().getMessageTypes().get(2);
        internal_static_netty_ProtoBody_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_netty_ProtoBody_descriptor,
                new String[]{"UserName", "ProductName", "Address", "HeaderMap",});
        internal_static_netty_ProtoBody_HeaderMapEntry_descriptor =
                internal_static_netty_ProtoBody_descriptor.getNestedTypes().get(0);
        internal_static_netty_ProtoBody_HeaderMapEntry_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_netty_ProtoBody_HeaderMapEntry_descriptor,
                new String[]{"Key", "Value",});
    }

    private SubscribeReqProto() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
    }

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    public interface SubscribeReqOrBuilder extends
            // @@protoc_insertion_point(interface_extends:netty.SubscribeReq)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>optional .netty.ProtoHeader header = 1;</code>
         */
        boolean hasHeader();

        /**
         * <code>optional .netty.ProtoHeader header = 1;</code>
         */
        ProtoHeader getHeader();

        /**
         * <code>optional .netty.ProtoHeader header = 1;</code>
         */
        ProtoHeaderOrBuilder getHeaderOrBuilder();

        /**
         * <code>optional .netty.ProtoBody body = 2;</code>
         */
        boolean hasBody();

        /**
         * <code>optional .netty.ProtoBody body = 2;</code>
         */
        ProtoBody getBody();

        /**
         * <code>optional .netty.ProtoBody body = 2;</code>
         */
        ProtoBodyOrBuilder getBodyOrBuilder();
    }

    public interface ProtoHeaderOrBuilder extends
            // @@protoc_insertion_point(interface_extends:netty.ProtoHeader)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>optional int32 subReqID = 1;</code>
         */
        int getSubReqID();

        /**
         * <code>optional .netty.ProtoHeader.MsgType msgType = 2;</code>
         * <p>
         * <pre>
         * enum
         * </pre>
         */
        int getMsgTypeValue();

        /**
         * <code>optional .netty.ProtoHeader.MsgType msgType = 2;</code>
         * <p>
         * <pre>
         * enum
         * </pre>
         */
        ProtoHeader.MsgType getMsgType();
    }

    public interface ProtoBodyOrBuilder extends
            // @@protoc_insertion_point(interface_extends:netty.ProtoBody)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>optional string userName = 1;</code>
         */
        String getUserName();

        /**
         * <code>optional string userName = 1;</code>
         */
        com.google.protobuf.ByteString
        getUserNameBytes();

        /**
         * <code>optional string productName = 2;</code>
         */
        String getProductName();

        /**
         * <code>optional string productName = 2;</code>
         */
        com.google.protobuf.ByteString
        getProductNameBytes();

        /**
         * <code>repeated string address = 3;</code>
         * <p>
         * <pre>
         * list
         * </pre>
         */
        com.google.protobuf.ProtocolStringList
        getAddressList();

        /**
         * <code>repeated string address = 3;</code>
         * <p>
         * <pre>
         * list
         * </pre>
         */
        int getAddressCount();

        /**
         * <code>repeated string address = 3;</code>
         * <p>
         * <pre>
         * list
         * </pre>
         */
        String getAddress(int index);

        /**
         * <code>repeated string address = 3;</code>
         * <p>
         * <pre>
         * list
         * </pre>
         */
        com.google.protobuf.ByteString
        getAddressBytes(int index);

        /**
         * <code>map&lt;string, .netty.ProtoHeader&gt; header_map = 4;</code>
         */
        java.util.Map<String, ProtoHeader>
        getHeaderMap();
    }

    /**
     * Protobuf type {@code netty.SubscribeReq}
     */
    public static final class SubscribeReq extends
            com.google.protobuf.GeneratedMessage implements
            // @@protoc_insertion_point(message_implements:netty.SubscribeReq)
            SubscribeReqOrBuilder {
        public static final int HEADER_FIELD_NUMBER = 1;
        public static final int BODY_FIELD_NUMBER = 2;
        public static final com.google.protobuf.Parser<SubscribeReq> PARSER =
                new com.google.protobuf.AbstractParser<SubscribeReq>() {
                    public SubscribeReq parsePartialFrom(
                            com.google.protobuf.CodedInputStream input,
                            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                            throws com.google.protobuf.InvalidProtocolBufferException {
                        try {
                            return new SubscribeReq(input, extensionRegistry);
                        } catch (RuntimeException e) {
                            if (e.getCause() instanceof
                                    com.google.protobuf.InvalidProtocolBufferException) {
                                throw (com.google.protobuf.InvalidProtocolBufferException)
                                        e.getCause();
                            }
                            throw e;
                        }
                    }
                };
        private static final long serialVersionUID = 0L;
        // @@protoc_insertion_point(class_scope:netty.SubscribeReq)
        private static final SubscribeReq DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new SubscribeReq();
        }

        private ProtoHeader header_;
        private ProtoBody body_;
        private byte memoizedIsInitialized = -1;
        private int memoizedSerializedSize = -1;

        // Use SubscribeReq.newBuilder() to construct.
        private SubscribeReq(com.google.protobuf.GeneratedMessage.Builder builder) {
            super(builder);
        }

        private SubscribeReq() {
        }

        private SubscribeReq(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
            this();
            int mutable_bitField0_ = 0;
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!input.skipField(tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            ProtoHeader.Builder subBuilder = null;
                            if (header_ != null) {
                                subBuilder = header_.toBuilder();
                            }
                            header_ = input.readMessage(ProtoHeader.PARSER, extensionRegistry);
                            if (subBuilder != null) {
                                subBuilder.mergeFrom(header_);
                                header_ = subBuilder.buildPartial();
                            }

                            break;
                        }
                        case 18: {
                            ProtoBody.Builder subBuilder = null;
                            if (body_ != null) {
                                subBuilder = body_.toBuilder();
                            }
                            body_ = input.readMessage(ProtoBody.PARSER, extensionRegistry);
                            if (subBuilder != null) {
                                subBuilder.mergeFrom(body_);
                                body_ = subBuilder.buildPartial();
                            }

                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw new RuntimeException(e.setUnfinishedMessage(this));
            } catch (java.io.IOException e) {
                throw new RuntimeException(
                        new com.google.protobuf.InvalidProtocolBufferException(
                                e.getMessage()).setUnfinishedMessage(this)
                );
            } finally {
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return SubscribeReqProto.internal_static_netty_SubscribeReq_descriptor;
        }

        public static SubscribeReq parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static SubscribeReq parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static SubscribeReq parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static SubscribeReq parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static SubscribeReq parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static SubscribeReq parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static SubscribeReq parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input);
        }

        public static SubscribeReq parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }

        public static SubscribeReq parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static SubscribeReq parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(SubscribeReq prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public static SubscribeReq getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return SubscribeReqProto.internal_static_netty_SubscribeReq_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            SubscribeReq.class, Builder.class);
        }

        /**
         * <code>optional .netty.ProtoHeader header = 1;</code>
         */
        public boolean hasHeader() {
            return header_ != null;
        }

        /**
         * <code>optional .netty.ProtoHeader header = 1;</code>
         */
        public ProtoHeader getHeader() {
            return header_ == null ? ProtoHeader.getDefaultInstance() : header_;
        }

        /**
         * <code>optional .netty.ProtoHeader header = 1;</code>
         */
        public ProtoHeaderOrBuilder getHeaderOrBuilder() {
            return getHeader();
        }

        /**
         * <code>optional .netty.ProtoBody body = 2;</code>
         */
        public boolean hasBody() {
            return body_ != null;
        }

        /**
         * <code>optional .netty.ProtoBody body = 2;</code>
         */
        public ProtoBody getBody() {
            return body_ == null ? ProtoBody.getDefaultInstance() : body_;
        }

        /**
         * <code>optional .netty.ProtoBody body = 2;</code>
         */
        public ProtoBodyOrBuilder getBodyOrBuilder() {
            return getBody();
        }

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (header_ != null) {
                output.writeMessage(1, getHeader());
            }
            if (body_ != null) {
                output.writeMessage(2, getBody());
            }
        }

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) return size;

            size = 0;
            if (header_ != null) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(1, getHeader());
            }
            if (body_ != null) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(2, getBody());
            }
            memoizedSerializedSize = size;
            return size;
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(
                BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        @Override
        public com.google.protobuf.Parser<SubscribeReq> getParserForType() {
            return PARSER;
        }

        public SubscribeReq getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

        /**
         * Protobuf type {@code netty.SubscribeReq}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:netty.SubscribeReq)
                SubscribeReqOrBuilder {
            private ProtoHeader header_ = null;
            private com.google.protobuf.SingleFieldBuilder<
                    ProtoHeader, ProtoHeader.Builder, ProtoHeaderOrBuilder> headerBuilder_;
            private ProtoBody body_ = null;
            private com.google.protobuf.SingleFieldBuilder<
                    ProtoBody, ProtoBody.Builder, ProtoBodyOrBuilder> bodyBuilder_;

            // Construct using com.lol.demo.encode.protobuf.SubscribeReqProto.SubscribeReq.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return SubscribeReqProto.internal_static_netty_SubscribeReq_descriptor;
            }

            protected FieldAccessorTable
            internalGetFieldAccessorTable() {
                return SubscribeReqProto.internal_static_netty_SubscribeReq_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                SubscribeReq.class, Builder.class);
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                if (headerBuilder_ == null) {
                    header_ = null;
                } else {
                    header_ = null;
                    headerBuilder_ = null;
                }
                if (bodyBuilder_ == null) {
                    body_ = null;
                } else {
                    body_ = null;
                    bodyBuilder_ = null;
                }
                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return SubscribeReqProto.internal_static_netty_SubscribeReq_descriptor;
            }

            public SubscribeReq getDefaultInstanceForType() {
                return SubscribeReq.getDefaultInstance();
            }

            public SubscribeReq build() {
                SubscribeReq result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public SubscribeReq buildPartial() {
                SubscribeReq result = new SubscribeReq(this);
                if (headerBuilder_ == null) {
                    result.header_ = header_;
                } else {
                    result.header_ = headerBuilder_.build();
                }
                if (bodyBuilder_ == null) {
                    result.body_ = body_;
                } else {
                    result.body_ = bodyBuilder_.build();
                }
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof SubscribeReq) {
                    return mergeFrom((SubscribeReq) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(SubscribeReq other) {
                if (other == SubscribeReq.getDefaultInstance()) return this;
                if (other.hasHeader()) {
                    mergeHeader(other.getHeader());
                }
                if (other.hasBody()) {
                    mergeBody(other.getBody());
                }
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                SubscribeReq parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (SubscribeReq) e.getUnfinishedMessage();
                    throw e;
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            /**
             * <code>optional .netty.ProtoHeader header = 1;</code>
             */
            public boolean hasHeader() {
                return headerBuilder_ != null || header_ != null;
            }

            /**
             * <code>optional .netty.ProtoHeader header = 1;</code>
             */
            public ProtoHeader getHeader() {
                if (headerBuilder_ == null) {
                    return header_ == null ? ProtoHeader.getDefaultInstance() : header_;
                } else {
                    return headerBuilder_.getMessage();
                }
            }

            /**
             * <code>optional .netty.ProtoHeader header = 1;</code>
             */
            public Builder setHeader(
                    ProtoHeader.Builder builderForValue) {
                if (headerBuilder_ == null) {
                    header_ = builderForValue.build();
                    onChanged();
                } else {
                    headerBuilder_.setMessage(builderForValue.build());
                }

                return this;
            }

            /**
             * <code>optional .netty.ProtoHeader header = 1;</code>
             */
            public Builder setHeader(ProtoHeader value) {
                if (headerBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    header_ = value;
                    onChanged();
                } else {
                    headerBuilder_.setMessage(value);
                }

                return this;
            }

            /**
             * <code>optional .netty.ProtoHeader header = 1;</code>
             */
            public Builder mergeHeader(ProtoHeader value) {
                if (headerBuilder_ == null) {
                    if (header_ != null) {
                        header_ =
                                ProtoHeader.newBuilder(header_).mergeFrom(value).buildPartial();
                    } else {
                        header_ = value;
                    }
                    onChanged();
                } else {
                    headerBuilder_.mergeFrom(value);
                }

                return this;
            }

            /**
             * <code>optional .netty.ProtoHeader header = 1;</code>
             */
            public Builder clearHeader() {
                if (headerBuilder_ == null) {
                    header_ = null;
                    onChanged();
                } else {
                    header_ = null;
                    headerBuilder_ = null;
                }

                return this;
            }

            /**
             * <code>optional .netty.ProtoHeader header = 1;</code>
             */
            public ProtoHeader.Builder getHeaderBuilder() {

                onChanged();
                return getHeaderFieldBuilder().getBuilder();
            }

            /**
             * <code>optional .netty.ProtoHeader header = 1;</code>
             */
            public ProtoHeaderOrBuilder getHeaderOrBuilder() {
                if (headerBuilder_ != null) {
                    return headerBuilder_.getMessageOrBuilder();
                } else {
                    return header_ == null ?
                            ProtoHeader.getDefaultInstance() : header_;
                }
            }

            /**
             * <code>optional .netty.ProtoHeader header = 1;</code>
             */
            private com.google.protobuf.SingleFieldBuilder<
                    ProtoHeader, ProtoHeader.Builder, ProtoHeaderOrBuilder>
            getHeaderFieldBuilder() {
                if (headerBuilder_ == null) {
                    headerBuilder_ = new com.google.protobuf.SingleFieldBuilder<
                            ProtoHeader, ProtoHeader.Builder, ProtoHeaderOrBuilder>(
                            getHeader(),
                            getParentForChildren(),
                            isClean());
                    header_ = null;
                }
                return headerBuilder_;
            }

            /**
             * <code>optional .netty.ProtoBody body = 2;</code>
             */
            public boolean hasBody() {
                return bodyBuilder_ != null || body_ != null;
            }

            /**
             * <code>optional .netty.ProtoBody body = 2;</code>
             */
            public ProtoBody getBody() {
                if (bodyBuilder_ == null) {
                    return body_ == null ? ProtoBody.getDefaultInstance() : body_;
                } else {
                    return bodyBuilder_.getMessage();
                }
            }

            /**
             * <code>optional .netty.ProtoBody body = 2;</code>
             */
            public Builder setBody(
                    ProtoBody.Builder builderForValue) {
                if (bodyBuilder_ == null) {
                    body_ = builderForValue.build();
                    onChanged();
                } else {
                    bodyBuilder_.setMessage(builderForValue.build());
                }

                return this;
            }

            /**
             * <code>optional .netty.ProtoBody body = 2;</code>
             */
            public Builder setBody(ProtoBody value) {
                if (bodyBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    body_ = value;
                    onChanged();
                } else {
                    bodyBuilder_.setMessage(value);
                }

                return this;
            }

            /**
             * <code>optional .netty.ProtoBody body = 2;</code>
             */
            public Builder mergeBody(ProtoBody value) {
                if (bodyBuilder_ == null) {
                    if (body_ != null) {
                        body_ =
                                ProtoBody.newBuilder(body_).mergeFrom(value).buildPartial();
                    } else {
                        body_ = value;
                    }
                    onChanged();
                } else {
                    bodyBuilder_.mergeFrom(value);
                }

                return this;
            }

            /**
             * <code>optional .netty.ProtoBody body = 2;</code>
             */
            public Builder clearBody() {
                if (bodyBuilder_ == null) {
                    body_ = null;
                    onChanged();
                } else {
                    body_ = null;
                    bodyBuilder_ = null;
                }

                return this;
            }

            /**
             * <code>optional .netty.ProtoBody body = 2;</code>
             */
            public ProtoBody.Builder getBodyBuilder() {

                onChanged();
                return getBodyFieldBuilder().getBuilder();
            }

            /**
             * <code>optional .netty.ProtoBody body = 2;</code>
             */
            public ProtoBodyOrBuilder getBodyOrBuilder() {
                if (bodyBuilder_ != null) {
                    return bodyBuilder_.getMessageOrBuilder();
                } else {
                    return body_ == null ?
                            ProtoBody.getDefaultInstance() : body_;
                }
            }

            /**
             * <code>optional .netty.ProtoBody body = 2;</code>
             */
            private com.google.protobuf.SingleFieldBuilder<
                    ProtoBody, ProtoBody.Builder, ProtoBodyOrBuilder>
            getBodyFieldBuilder() {
                if (bodyBuilder_ == null) {
                    bodyBuilder_ = new com.google.protobuf.SingleFieldBuilder<
                            ProtoBody, ProtoBody.Builder, ProtoBodyOrBuilder>(
                            getBody(),
                            getParentForChildren(),
                            isClean());
                    body_ = null;
                }
                return bodyBuilder_;
            }

            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }


            // @@protoc_insertion_point(builder_scope:netty.SubscribeReq)
        }

    }

    /**
     * Protobuf type {@code netty.ProtoHeader}
     */
    public static final class ProtoHeader extends
            com.google.protobuf.GeneratedMessage implements
            // @@protoc_insertion_point(message_implements:netty.ProtoHeader)
            ProtoHeaderOrBuilder {
        public static final int SUBREQID_FIELD_NUMBER = 1;
        public static final int MSGTYPE_FIELD_NUMBER = 2;
        public static final com.google.protobuf.Parser<ProtoHeader> PARSER =
                new com.google.protobuf.AbstractParser<ProtoHeader>() {
                    public ProtoHeader parsePartialFrom(
                            com.google.protobuf.CodedInputStream input,
                            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                            throws com.google.protobuf.InvalidProtocolBufferException {
                        try {
                            return new ProtoHeader(input, extensionRegistry);
                        } catch (RuntimeException e) {
                            if (e.getCause() instanceof
                                    com.google.protobuf.InvalidProtocolBufferException) {
                                throw (com.google.protobuf.InvalidProtocolBufferException)
                                        e.getCause();
                            }
                            throw e;
                        }
                    }
                };
        private static final long serialVersionUID = 0L;
        // @@protoc_insertion_point(class_scope:netty.ProtoHeader)
        private static final ProtoHeader DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new ProtoHeader();
        }

        private int subReqID_;
        private int msgType_;
        private byte memoizedIsInitialized = -1;
        private int memoizedSerializedSize = -1;

        // Use ProtoHeader.newBuilder() to construct.
        private ProtoHeader(com.google.protobuf.GeneratedMessage.Builder builder) {
            super(builder);
        }

        private ProtoHeader() {
            subReqID_ = 0;
            msgType_ = 0;
        }

        private ProtoHeader(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
            this();
            int mutable_bitField0_ = 0;
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!input.skipField(tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 8: {

                            subReqID_ = input.readInt32();
                            break;
                        }
                        case 16: {
                            int rawValue = input.readEnum();

                            msgType_ = rawValue;
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw new RuntimeException(e.setUnfinishedMessage(this));
            } catch (java.io.IOException e) {
                throw new RuntimeException(
                        new com.google.protobuf.InvalidProtocolBufferException(
                                e.getMessage()).setUnfinishedMessage(this)
                );
            } finally {
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return SubscribeReqProto.internal_static_netty_ProtoHeader_descriptor;
        }

        public static ProtoHeader parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static ProtoHeader parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static ProtoHeader parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static ProtoHeader parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static ProtoHeader parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static ProtoHeader parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static ProtoHeader parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input);
        }

        public static ProtoHeader parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }

        public static ProtoHeader parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static ProtoHeader parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(ProtoHeader prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public static ProtoHeader getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return SubscribeReqProto.internal_static_netty_ProtoHeader_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            ProtoHeader.class, Builder.class);
        }

        /**
         * <code>optional int32 subReqID = 1;</code>
         */
        public int getSubReqID() {
            return subReqID_;
        }

        /**
         * <code>optional .netty.ProtoHeader.MsgType msgType = 2;</code>
         * <p>
         * <pre>
         * enum
         * </pre>
         */
        public int getMsgTypeValue() {
            return msgType_;
        }

        /**
         * <code>optional .netty.ProtoHeader.MsgType msgType = 2;</code>
         * <p>
         * <pre>
         * enum
         * </pre>
         */
        public MsgType getMsgType() {
            MsgType result = MsgType.valueOf(msgType_);
            return result == null ? MsgType.UNRECOGNIZED : result;
        }

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (subReqID_ != 0) {
                output.writeInt32(1, subReqID_);
            }
            if (msgType_ != MsgType.DEFAULT.getNumber()) {
                output.writeEnum(2, msgType_);
            }
        }

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) return size;

            size = 0;
            if (subReqID_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(1, subReqID_);
            }
            if (msgType_ != MsgType.DEFAULT.getNumber()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeEnumSize(2, msgType_);
            }
            memoizedSerializedSize = size;
            return size;
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(
                BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        @Override
        public com.google.protobuf.Parser<ProtoHeader> getParserForType() {
            return PARSER;
        }

        public ProtoHeader getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

        /**
         * Protobuf enum {@code netty.ProtoHeader.MsgType}
         */
        public enum MsgType
                implements com.google.protobuf.ProtocolMessageEnum {
            /**
             * <code>DEFAULT = 0;</code>
             */
            DEFAULT(0, 0),
            /**
             * <code>LOGIN_REQ = 1;</code>
             */
            LOGIN_REQ(1, 1),
            /**
             * <code>LOGIN_RESP = 2;</code>
             */
            LOGIN_RESP(2, 2),
            /**
             * <code>LOGIN_OK = 3;</code>
             */
            LOGIN_OK(3, 3),
            /**
             * <code>LOGIN_OUT_OF_WHITE_IP = 4;</code>
             */
            LOGIN_OUT_OF_WHITE_IP(4, 4),
            /**
             * <code>LOGIN_DENY = 5;</code>
             */
            LOGIN_DENY(5, 5),
            /**
             * <code>HEARTBEAT_REQ = 6;</code>
             */
            HEARTBEAT_REQ(6, 6),
            /**
             * <code>HEARTBEAT_RESP = 7;</code>
             */
            HEARTBEAT_RESP(7, 7),
            /**
             * <code>GAME_REQ = 8;</code>
             */
            GAME_REQ(8, 8),
            /**
             * <code>GAME_RESP = 9;</code>
             */
            GAME_RESP(9, 9),
            UNRECOGNIZED(-1, -1),;

            /**
             * <code>DEFAULT = 0;</code>
             */
            public static final int DEFAULT_VALUE = 0;
            /**
             * <code>LOGIN_REQ = 1;</code>
             */
            public static final int LOGIN_REQ_VALUE = 1;
            /**
             * <code>LOGIN_RESP = 2;</code>
             */
            public static final int LOGIN_RESP_VALUE = 2;
            /**
             * <code>LOGIN_OK = 3;</code>
             */
            public static final int LOGIN_OK_VALUE = 3;
            /**
             * <code>LOGIN_OUT_OF_WHITE_IP = 4;</code>
             */
            public static final int LOGIN_OUT_OF_WHITE_IP_VALUE = 4;
            /**
             * <code>LOGIN_DENY = 5;</code>
             */
            public static final int LOGIN_DENY_VALUE = 5;
            /**
             * <code>HEARTBEAT_REQ = 6;</code>
             */
            public static final int HEARTBEAT_REQ_VALUE = 6;
            /**
             * <code>HEARTBEAT_RESP = 7;</code>
             */
            public static final int HEARTBEAT_RESP_VALUE = 7;
            /**
             * <code>GAME_REQ = 8;</code>
             */
            public static final int GAME_REQ_VALUE = 8;
            /**
             * <code>GAME_RESP = 9;</code>
             */
            public static final int GAME_RESP_VALUE = 9;
            private static final MsgType[] VALUES = values();
            private static com.google.protobuf.Internal.EnumLiteMap<MsgType>
                    internalValueMap =
                    new com.google.protobuf.Internal.EnumLiteMap<MsgType>() {
                        public MsgType findValueByNumber(int number) {
                            return MsgType.valueOf(number);
                        }
                    };
            private final int index;
            private final int value;

            private MsgType(int index, int value) {
                this.index = index;
                this.value = value;
            }

            public static MsgType valueOf(int value) {
                switch (value) {
                    case 0:
                        return DEFAULT;
                    case 1:
                        return LOGIN_REQ;
                    case 2:
                        return LOGIN_RESP;
                    case 3:
                        return LOGIN_OK;
                    case 4:
                        return LOGIN_OUT_OF_WHITE_IP;
                    case 5:
                        return LOGIN_DENY;
                    case 6:
                        return HEARTBEAT_REQ;
                    case 7:
                        return HEARTBEAT_RESP;
                    case 8:
                        return GAME_REQ;
                    case 9:
                        return GAME_RESP;
                    default:
                        return null;
                }
            }

            public static com.google.protobuf.Internal.EnumLiteMap<MsgType>
            internalGetValueMap() {
                return internalValueMap;
            }

            public static final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptor() {
                return ProtoHeader.getDescriptor().getEnumTypes().get(0);
            }

            public static MsgType valueOf(
                    com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
                if (desc.getType() != getDescriptor()) {
                    throw new IllegalArgumentException(
                            "EnumValueDescriptor is not for this type.");
                }
                if (desc.getIndex() == -1) {
                    return UNRECOGNIZED;
                }
                return VALUES[desc.getIndex()];
            }

            public final int getNumber() {
                if (index == -1) {
                    throw new IllegalArgumentException(
                            "Can't get the number of an unknown enum value.");
                }
                return value;
            }

            public final com.google.protobuf.Descriptors.EnumValueDescriptor
            getValueDescriptor() {
                return getDescriptor().getValues().get(index);
            }

            public final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptorForType() {
                return getDescriptor();
            }

            // @@protoc_insertion_point(enum_scope:netty.ProtoHeader.MsgType)
        }

        /**
         * Protobuf type {@code netty.ProtoHeader}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:netty.ProtoHeader)
                ProtoHeaderOrBuilder {
            private int subReqID_;
            private int msgType_ = 0;

            // Construct using com.lol.demo.encode.protobuf.SubscribeReqProto.ProtoHeader.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return SubscribeReqProto.internal_static_netty_ProtoHeader_descriptor;
            }

            protected FieldAccessorTable
            internalGetFieldAccessorTable() {
                return SubscribeReqProto.internal_static_netty_ProtoHeader_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                ProtoHeader.class, Builder.class);
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                subReqID_ = 0;

                msgType_ = 0;

                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return SubscribeReqProto.internal_static_netty_ProtoHeader_descriptor;
            }

            public ProtoHeader getDefaultInstanceForType() {
                return ProtoHeader.getDefaultInstance();
            }

            public ProtoHeader build() {
                ProtoHeader result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public ProtoHeader buildPartial() {
                ProtoHeader result = new ProtoHeader(this);
                result.subReqID_ = subReqID_;
                result.msgType_ = msgType_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof ProtoHeader) {
                    return mergeFrom((ProtoHeader) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(ProtoHeader other) {
                if (other == ProtoHeader.getDefaultInstance()) return this;
                if (other.getSubReqID() != 0) {
                    setSubReqID(other.getSubReqID());
                }
                if (other.msgType_ != 0) {
                    setMsgTypeValue(other.getMsgTypeValue());
                }
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                ProtoHeader parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (ProtoHeader) e.getUnfinishedMessage();
                    throw e;
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            /**
             * <code>optional int32 subReqID = 1;</code>
             */
            public int getSubReqID() {
                return subReqID_;
            }

            /**
             * <code>optional int32 subReqID = 1;</code>
             */
            public Builder setSubReqID(int value) {

                subReqID_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional int32 subReqID = 1;</code>
             */
            public Builder clearSubReqID() {

                subReqID_ = 0;
                onChanged();
                return this;
            }

            /**
             * <code>optional .netty.ProtoHeader.MsgType msgType = 2;</code>
             * <p>
             * <pre>
             * enum
             * </pre>
             */
            public int getMsgTypeValue() {
                return msgType_;
            }

            /**
             * <code>optional .netty.ProtoHeader.MsgType msgType = 2;</code>
             * <p>
             * <pre>
             * enum
             * </pre>
             */
            public Builder setMsgTypeValue(int value) {
                msgType_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional .netty.ProtoHeader.MsgType msgType = 2;</code>
             * <p>
             * <pre>
             * enum
             * </pre>
             */
            public MsgType getMsgType() {
                MsgType result = MsgType.valueOf(msgType_);
                return result == null ? MsgType.UNRECOGNIZED : result;
            }

            /**
             * <code>optional .netty.ProtoHeader.MsgType msgType = 2;</code>
             * <p>
             * <pre>
             * enum
             * </pre>
             */
            public Builder setMsgType(MsgType value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                msgType_ = value.getNumber();
                onChanged();
                return this;
            }

            /**
             * <code>optional .netty.ProtoHeader.MsgType msgType = 2;</code>
             * <p>
             * <pre>
             * enum
             * </pre>
             */
            public Builder clearMsgType() {

                msgType_ = 0;
                onChanged();
                return this;
            }

            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }


            // @@protoc_insertion_point(builder_scope:netty.ProtoHeader)
        }

    }

    /**
     * Protobuf type {@code netty.ProtoBody}
     */
    public static final class ProtoBody extends
            com.google.protobuf.GeneratedMessage implements
            // @@protoc_insertion_point(message_implements:netty.ProtoBody)
            ProtoBodyOrBuilder {
        public static final int USERNAME_FIELD_NUMBER = 1;
        public static final int PRODUCTNAME_FIELD_NUMBER = 2;
        public static final int ADDRESS_FIELD_NUMBER = 3;
        public static final int HEADER_MAP_FIELD_NUMBER = 4;
        public static final com.google.protobuf.Parser<ProtoBody> PARSER =
                new com.google.protobuf.AbstractParser<ProtoBody>() {
                    public ProtoBody parsePartialFrom(
                            com.google.protobuf.CodedInputStream input,
                            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                            throws com.google.protobuf.InvalidProtocolBufferException {
                        try {
                            return new ProtoBody(input, extensionRegistry);
                        } catch (RuntimeException e) {
                            if (e.getCause() instanceof
                                    com.google.protobuf.InvalidProtocolBufferException) {
                                throw (com.google.protobuf.InvalidProtocolBufferException)
                                        e.getCause();
                            }
                            throw e;
                        }
                    }
                };
        private static final long serialVersionUID = 0L;
        // @@protoc_insertion_point(class_scope:netty.ProtoBody)
        private static final ProtoBody DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new ProtoBody();
        }

        private int bitField0_;
        private volatile Object userName_;
        private volatile Object productName_;
        private com.google.protobuf.LazyStringList address_;
        private com.google.protobuf.MapField<
                String, ProtoHeader> headerMap_;
        private byte memoizedIsInitialized = -1;
        private int memoizedSerializedSize = -1;

        // Use ProtoBody.newBuilder() to construct.
        private ProtoBody(com.google.protobuf.GeneratedMessage.Builder builder) {
            super(builder);
        }

        private ProtoBody() {
            userName_ = "";
            productName_ = "";
            address_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        }

        private ProtoBody(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
            this();
            int mutable_bitField0_ = 0;
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!input.skipField(tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            com.google.protobuf.ByteString bs = input.readBytes();

                            userName_ = bs;
                            break;
                        }
                        case 18: {
                            com.google.protobuf.ByteString bs = input.readBytes();

                            productName_ = bs;
                            break;
                        }
                        case 26: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                                address_ = new com.google.protobuf.LazyStringArrayList();
                                mutable_bitField0_ |= 0x00000004;
                            }
                            address_.add(bs);
                            break;
                        }
                        case 34: {
                            if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                                headerMap_ = com.google.protobuf.MapField.newMapField(
                                        HeaderMapDefaultEntryHolder.defaultEntry);
                                mutable_bitField0_ |= 0x00000008;
                            }
                            com.google.protobuf.MapEntry<String, ProtoHeader>
                                    headerMap = input.readMessage(
                                    HeaderMapDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                            headerMap_.getMutableMap().put(headerMap.getKey(), headerMap.getValue());
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw new RuntimeException(e.setUnfinishedMessage(this));
            } catch (java.io.IOException e) {
                throw new RuntimeException(
                        new com.google.protobuf.InvalidProtocolBufferException(
                                e.getMessage()).setUnfinishedMessage(this)
                );
            } finally {
                if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                    address_ = address_.getUnmodifiableView();
                }
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return SubscribeReqProto.internal_static_netty_ProtoBody_descriptor;
        }

        public static ProtoBody parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static ProtoBody parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static ProtoBody parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static ProtoBody parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static ProtoBody parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static ProtoBody parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static ProtoBody parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input);
        }

        public static ProtoBody parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }

        public static ProtoBody parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static ProtoBody parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(ProtoBody prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public static ProtoBody getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        @SuppressWarnings({"rawtypes"})
        protected com.google.protobuf.MapField internalGetMapField(
                int number) {
            switch (number) {
                case 4:
                    return internalGetHeaderMap();
                default:
                    throw new RuntimeException(
                            "Invalid map field number: " + number);
            }
        }

        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return SubscribeReqProto.internal_static_netty_ProtoBody_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            ProtoBody.class, Builder.class);
        }

        /**
         * <code>optional string userName = 1;</code>
         */
        public String getUserName() {
            Object ref = userName_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    userName_ = s;
                }
                return s;
            }
        }

        /**
         * <code>optional string userName = 1;</code>
         */
        public com.google.protobuf.ByteString
        getUserNameBytes() {
            Object ref = userName_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                userName_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>optional string productName = 2;</code>
         */
        public String getProductName() {
            Object ref = productName_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    productName_ = s;
                }
                return s;
            }
        }

        /**
         * <code>optional string productName = 2;</code>
         */
        public com.google.protobuf.ByteString
        getProductNameBytes() {
            Object ref = productName_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                productName_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>repeated string address = 3;</code>
         * <p>
         * <pre>
         * list
         * </pre>
         */
        public com.google.protobuf.ProtocolStringList
        getAddressList() {
            return address_;
        }

        /**
         * <code>repeated string address = 3;</code>
         * <p>
         * <pre>
         * list
         * </pre>
         */
        public int getAddressCount() {
            return address_.size();
        }

        /**
         * <code>repeated string address = 3;</code>
         * <p>
         * <pre>
         * list
         * </pre>
         */
        public String getAddress(int index) {
            return address_.get(index);
        }

        /**
         * <code>repeated string address = 3;</code>
         * <p>
         * <pre>
         * list
         * </pre>
         */
        public com.google.protobuf.ByteString
        getAddressBytes(int index) {
            return address_.getByteString(index);
        }

        private com.google.protobuf.MapField<String, ProtoHeader>
        internalGetHeaderMap() {
            if (headerMap_ == null) {
                return com.google.protobuf.MapField.emptyMapField(
                        HeaderMapDefaultEntryHolder.defaultEntry);
            }
            return headerMap_;
        }

        /**
         * <code>map&lt;string, .netty.ProtoHeader&gt; header_map = 4;</code>
         */

        public java.util.Map<String, ProtoHeader> getHeaderMap() {
            return internalGetHeaderMap().getMap();
        }

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (!getUserNameBytes().isEmpty()) {
                output.writeBytes(1, getUserNameBytes());
            }
            if (!getProductNameBytes().isEmpty()) {
                output.writeBytes(2, getProductNameBytes());
            }
            for (int i = 0; i < address_.size(); i++) {
                output.writeBytes(3, address_.getByteString(i));
            }
            for (java.util.Map.Entry<String, ProtoHeader> entry
                    : internalGetHeaderMap().getMap().entrySet()) {
                com.google.protobuf.MapEntry<String, ProtoHeader>
                        headerMap = HeaderMapDefaultEntryHolder.defaultEntry.newBuilderForType()
                        .setKey(entry.getKey())
                        .setValue(entry.getValue())
                        .build();
                output.writeMessage(4, headerMap);
            }
        }

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) return size;

            size = 0;
            if (!getUserNameBytes().isEmpty()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(1, getUserNameBytes());
            }
            if (!getProductNameBytes().isEmpty()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(2, getProductNameBytes());
            }
            {
                int dataSize = 0;
                for (int i = 0; i < address_.size(); i++) {
                    dataSize += com.google.protobuf.CodedOutputStream
                            .computeBytesSizeNoTag(address_.getByteString(i));
                }
                size += dataSize;
                size += 1 * getAddressList().size();
            }
            for (java.util.Map.Entry<String, ProtoHeader> entry
                    : internalGetHeaderMap().getMap().entrySet()) {
                com.google.protobuf.MapEntry<String, ProtoHeader>
                        headerMap = HeaderMapDefaultEntryHolder.defaultEntry.newBuilderForType()
                        .setKey(entry.getKey())
                        .setValue(entry.getValue())
                        .build();
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(4, headerMap);
            }
            memoizedSerializedSize = size;
            return size;
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(
                BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        @Override
        public com.google.protobuf.Parser<ProtoBody> getParserForType() {
            return PARSER;
        }

        public ProtoBody getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

        private static final class HeaderMapDefaultEntryHolder {
            static final com.google.protobuf.MapEntry<
                    String, ProtoHeader> defaultEntry =
                    com.google.protobuf.MapEntry
                            .<String, ProtoHeader>newDefaultInstance(
                                    SubscribeReqProto.internal_static_netty_ProtoBody_HeaderMapEntry_descriptor,
                                    com.google.protobuf.WireFormat.FieldType.STRING,
                                    "",
                                    com.google.protobuf.WireFormat.FieldType.MESSAGE,
                                    ProtoHeader.getDefaultInstance());
        }

        /**
         * Protobuf type {@code netty.ProtoBody}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:netty.ProtoBody)
                ProtoBodyOrBuilder {
            private int bitField0_;
            private Object userName_ = "";
            private Object productName_ = "";
            private com.google.protobuf.LazyStringList address_ = com.google.protobuf.LazyStringArrayList.EMPTY;
            private com.google.protobuf.MapField<
                    String, ProtoHeader> headerMap_;

            // Construct using com.lol.demo.encode.protobuf.SubscribeReqProto.ProtoBody.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return SubscribeReqProto.internal_static_netty_ProtoBody_descriptor;
            }

            @SuppressWarnings({"rawtypes"})
            protected com.google.protobuf.MapField internalGetMapField(
                    int number) {
                switch (number) {
                    case 4:
                        return internalGetHeaderMap();
                    default:
                        throw new RuntimeException(
                                "Invalid map field number: " + number);
                }
            }

            @SuppressWarnings({"rawtypes"})
            protected com.google.protobuf.MapField internalGetMutableMapField(
                    int number) {
                switch (number) {
                    case 4:
                        return internalGetMutableHeaderMap();
                    default:
                        throw new RuntimeException(
                                "Invalid map field number: " + number);
                }
            }

            protected FieldAccessorTable
            internalGetFieldAccessorTable() {
                return SubscribeReqProto.internal_static_netty_ProtoBody_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                ProtoBody.class, Builder.class);
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                userName_ = "";

                productName_ = "";

                address_ = com.google.protobuf.LazyStringArrayList.EMPTY;
                bitField0_ = (bitField0_ & ~0x00000004);
                internalGetMutableHeaderMap().clear();
                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return SubscribeReqProto.internal_static_netty_ProtoBody_descriptor;
            }

            public ProtoBody getDefaultInstanceForType() {
                return ProtoBody.getDefaultInstance();
            }

            public ProtoBody build() {
                ProtoBody result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public ProtoBody buildPartial() {
                ProtoBody result = new ProtoBody(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                result.userName_ = userName_;
                result.productName_ = productName_;
                if (((bitField0_ & 0x00000004) == 0x00000004)) {
                    address_ = address_.getUnmodifiableView();
                    bitField0_ = (bitField0_ & ~0x00000004);
                }
                result.address_ = address_;
                result.headerMap_ = internalGetHeaderMap();
                result.headerMap_.makeImmutable();
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof ProtoBody) {
                    return mergeFrom((ProtoBody) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(ProtoBody other) {
                if (other == ProtoBody.getDefaultInstance()) return this;
                if (!other.getUserName().isEmpty()) {
                    userName_ = other.userName_;
                    onChanged();
                }
                if (!other.getProductName().isEmpty()) {
                    productName_ = other.productName_;
                    onChanged();
                }
                if (!other.address_.isEmpty()) {
                    if (address_.isEmpty()) {
                        address_ = other.address_;
                        bitField0_ = (bitField0_ & ~0x00000004);
                    } else {
                        ensureAddressIsMutable();
                        address_.addAll(other.address_);
                    }
                    onChanged();
                }
                internalGetMutableHeaderMap().mergeFrom(
                        other.internalGetHeaderMap());
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                ProtoBody parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (ProtoBody) e.getUnfinishedMessage();
                    throw e;
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            /**
             * <code>optional string userName = 1;</code>
             */
            public String getUserName() {
                Object ref = userName_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        userName_ = s;
                    }
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>optional string userName = 1;</code>
             */
            public Builder setUserName(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                userName_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string userName = 1;</code>
             */
            public com.google.protobuf.ByteString
            getUserNameBytes() {
                Object ref = userName_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    userName_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string userName = 1;</code>
             */
            public Builder setUserNameBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                userName_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string userName = 1;</code>
             */
            public Builder clearUserName() {

                userName_ = getDefaultInstance().getUserName();
                onChanged();
                return this;
            }

            /**
             * <code>optional string productName = 2;</code>
             */
            public String getProductName() {
                Object ref = productName_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        productName_ = s;
                    }
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>optional string productName = 2;</code>
             */
            public Builder setProductName(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                productName_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string productName = 2;</code>
             */
            public com.google.protobuf.ByteString
            getProductNameBytes() {
                Object ref = productName_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    productName_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string productName = 2;</code>
             */
            public Builder setProductNameBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                productName_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string productName = 2;</code>
             */
            public Builder clearProductName() {

                productName_ = getDefaultInstance().getProductName();
                onChanged();
                return this;
            }

            private void ensureAddressIsMutable() {
                if (!((bitField0_ & 0x00000004) == 0x00000004)) {
                    address_ = new com.google.protobuf.LazyStringArrayList(address_);
                    bitField0_ |= 0x00000004;
                }
            }

            /**
             * <code>repeated string address = 3;</code>
             * <p>
             * <pre>
             * list
             * </pre>
             */
            public com.google.protobuf.ProtocolStringList
            getAddressList() {
                return address_.getUnmodifiableView();
            }

            /**
             * <code>repeated string address = 3;</code>
             * <p>
             * <pre>
             * list
             * </pre>
             */
            public int getAddressCount() {
                return address_.size();
            }

            /**
             * <code>repeated string address = 3;</code>
             * <p>
             * <pre>
             * list
             * </pre>
             */
            public String getAddress(int index) {
                return address_.get(index);
            }

            /**
             * <code>repeated string address = 3;</code>
             * <p>
             * <pre>
             * list
             * </pre>
             */
            public com.google.protobuf.ByteString
            getAddressBytes(int index) {
                return address_.getByteString(index);
            }

            /**
             * <code>repeated string address = 3;</code>
             * <p>
             * <pre>
             * list
             * </pre>
             */
            public Builder setAddress(
                    int index, String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureAddressIsMutable();
                address_.set(index, value);
                onChanged();
                return this;
            }

            /**
             * <code>repeated string address = 3;</code>
             * <p>
             * <pre>
             * list
             * </pre>
             */
            public Builder addAddress(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureAddressIsMutable();
                address_.add(value);
                onChanged();
                return this;
            }

            /**
             * <code>repeated string address = 3;</code>
             * <p>
             * <pre>
             * list
             * </pre>
             */
            public Builder addAllAddress(
                    Iterable<String> values) {
                ensureAddressIsMutable();
                com.google.protobuf.AbstractMessageLite.Builder.addAll(
                        values, address_);
                onChanged();
                return this;
            }

            /**
             * <code>repeated string address = 3;</code>
             * <p>
             * <pre>
             * list
             * </pre>
             */
            public Builder clearAddress() {
                address_ = com.google.protobuf.LazyStringArrayList.EMPTY;
                bitField0_ = (bitField0_ & ~0x00000004);
                onChanged();
                return this;
            }

            /**
             * <code>repeated string address = 3;</code>
             * <p>
             * <pre>
             * list
             * </pre>
             */
            public Builder addAddressBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureAddressIsMutable();
                address_.add(value);
                onChanged();
                return this;
            }

            private com.google.protobuf.MapField<String, ProtoHeader>
            internalGetHeaderMap() {
                if (headerMap_ == null) {
                    return com.google.protobuf.MapField.emptyMapField(
                            HeaderMapDefaultEntryHolder.defaultEntry);
                }
                return headerMap_;
            }

            private com.google.protobuf.MapField<String, ProtoHeader>
            internalGetMutableHeaderMap() {
                onChanged();
                ;
                if (headerMap_ == null) {
                    headerMap_ = com.google.protobuf.MapField.newMapField(
                            HeaderMapDefaultEntryHolder.defaultEntry);
                }
                if (!headerMap_.isMutable()) {
                    headerMap_ = headerMap_.copy();
                }
                return headerMap_;
            }

            /**
             * <code>map&lt;string, .netty.ProtoHeader&gt; header_map = 4;</code>
             */
            public java.util.Map<String, ProtoHeader> getHeaderMap() {
                return internalGetHeaderMap().getMap();
            }

            /**
             * <code>map&lt;string, .netty.ProtoHeader&gt; header_map = 4;</code>
             */
            public java.util.Map<String, ProtoHeader>
            getMutableHeaderMap() {
                return internalGetMutableHeaderMap().getMutableMap();
            }

            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }


            // @@protoc_insertion_point(builder_scope:netty.ProtoBody)
        }

    }

    // @@protoc_insertion_point(outer_class_scope)
}
